In [33]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import explained_variance_score

In [34]:
datos = pd.read_csv("tic-tac-toe.data.txt", header = None)

In [35]:
datos.head()

   0  1  2  3  4  5  6  7  8         9
0  x  x  x  x  o  o  x  o  o  positive
1  x  x  x  x  o  o  o  x  o  positive
2  x  x  x  x  o  o  o  o  x  positive
3  x  x  x  x  o  o  o  b  b  positive
4  x  x  x  x  o  o  b  o  b  positive

In [36]:
datos.dtypes

0    object
1    object
2    object
3    object
4    object
5    object
6    object
7    object
8    object
9    object
dtype: object

In [37]:
funcion = preprocessing.LabelEncoder()
for f in datos:
    datos[f] = funcion.fit_transform(datos[f].astype(str))  
datos.head()

   0  1  2  3  4  5  6  7  8  9
0  2  2  2  2  1  1  2  1  1  1
1  2  2  2  2  1  1  1  2  1  1
2  2  2  2  2  1  1  1  1  2  1
3  2  2  2  2  1  1  1  0  0  1
4  2  2  2  2  1  1  0  1  0  1

In [38]:
y = datos.pop(9)

In [39]:
modelos = []
modelos.append(("Lineal",LinearRegression()))
modelos.append(("Ridge", Ridge()))
modelos.append(("Lasso",Lasso()))
modelos.append(("ElasticNet",ElasticNet()))
modelos.append(("Forest",RandomForestRegressor()))
modelos.append(("Baggin",BaggingRegressor()))
modelos.append(("extree",ExtraTreesRegressor()))
modelos.append(("arbol",DecisionTreeRegressor()))
modelos.append(("SVR",SVR()))
modelos.append(("Knn",KNeighborsRegressor()))


for nombre, modelo in modelos:
    
    modelo.fit(datos,y)
    prediccion = modelo.predict(datos)
    score = explained_variance_score(y,prediccion)
    error = mean_absolute_error(prediccion, y)
    
    print("modelo %s: %f , error: %f"% (nombre,score,error))

modelo Lineal: 0.062227 , error: 0.424726
modelo Ridge: 0.062227 , error: 0.424774
modelo Lasso: 0.000000 , error: 0.452909
modelo ElasticNet: 0.000000 , error: 0.452909
modelo Forest: 0.960935 , error: 0.045720
modelo Baggin: 0.959907 , error: 0.045094
modelo extree: 1.000000 , error: 0.000000
modelo arbol: 1.000000 , error: 0.000000
modelo SVR: 0.837811 , error: 0.144020
modelo Knn: 0.483530 , error: 0.219833